routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WebController::class, 'index'])->name('index');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'home'])->name('home');
    // user settings for newsfeeds
    Route::resource('/settings', SettingsController::class);
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-white">
                        <h4 class="mt-2">
                            Top Headlines
                            @if(Auth::user()->settings)
                                <small class="text-primary">(Displaying articles based on user settings)</small>
                            @else
                                <small class="text-primary">(Displaying live articles as user does not applied settings yet)</small>
                            @endif
                            <small class="pull-right">Scope: <span class="text-primary">Private</span>, Reader: <span class="text-primary">{{ Auth::user()->name }}</span></small>
                        </h4>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <div class="row">
                            @if(count($articles) > 0)
                                @foreach($articles as $n => $article)
                                    <div class="col-lg-4 col-md-6 mb-3">
                                        <div class="card">
                                            <img class="card-img-top" src="{{ !empty($article['urlToImage']) ? $article['urlToImage'] : asset('img/image-not-found.png') }}" alt="{{ $article['title'] }}">
                                            <div class="card-body">
                                                <h4 class="card-title">{{ $article['title'] }}</h4>
                                                <div class="text-primary">
                                                    <small>Source: {{ $article['source']['name'] ? $article['source']['name'] : 'Source not found' }}</small> <br>
                                                    <small>Country: </small>
                                                    @if($article['source'] && !empty($article['source']['country']))
                                                        <small class="text-success">{{ countries()[$article['source']['country']] }}</small>
                                                    @else
                                                        <small class="text-danger">Not Available</small>
                                                    @endif
                                                    <small class="pull-right">{{ $article['publishedAt'] }}</small>
                                                </div>
                                                <a href="{{ $article['url'] }}" target="_blank" class="card-link pull-right">read more ...</a>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach

                                @if(Auth::check() && !empty(Auth::user()->settings))
                                
                                {{ $articles->links('pagination::bootstrap-4') }}

                                @endif
                            @endif
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-white text-center">
                        <h4 class="mt-5">
                            This is a sample newsfeed portal.
                        </h4>
                        <h4 class="mt-5 mb-5">
                            Please, register / login to see the newsfeeds.
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/settings.blade.php
@extends('layouts.app')

@push('styles')
    <link href="{{ asset('plugins/select2/select2.min.css') }}" rel="stylesheet" />
@endpush

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @if (session('status'))
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ session('status') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header bg-white">
                    <h4 class="mt-2">
                        Settings
                    </h4>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h5>Selected Countries <small class="text-secondary">(2-letter ISO 3166-1 code)</small></h5>
                            @if(!empty($settings) && !empty($settings->countries))
                                @php $countries = explode(',', $settings->countries) @endphp
                                @foreach($countries as $country)
                                    <span class="badge badge-md bg-secondary p-2 mb-1 text-uppercase">{{ $country }}</span>
                                @endforeach
                            @else
                                <div>No country is selected!</div>
                            @endif
                        </li>
                        <li class="list-group-item">
                            <h5>Selected Sources</h5>
                            @if(!empty($settings) && !empty($settings->sources))
                                @foreach(explode(',', $settings->sources) as $get_source)
                                    <span class="badge badge-md bg-secondary p-2 mb-1 text-uppercase">{{ $get_source }}</span>
                                @endforeach
                            @else
                                <div>No source is selected!</div>
                            @endif
                        </li>
                        <li class="list-group-item">
                            <h5>Expected keywords</h5>
                            <div>{{ !empty($settings) && !empty($settings->keywords) ? $settings->keywords : 'No keyword is set!' }}</div>
                        </li>
                        <li class="list-group-item text-primary">
                            This above criterias will set your newsfeeds in your private newsfeeds page. 
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header bg-white">
                    <h4 class="mt-2">
                        Update Settings
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('settings.store') }}">
                        @csrf
                        <div class="mb-3">
                            <label for="countries" class="form-label">Countries</label>
                            <select class="form-control select-2" id="countries" name="countries[]" multiple="" required>
                                @foreach(countries() as $c => $country)
                                    <option value="{{ $c }}">{{ $country }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="sources" class="form-label">Sources</label>
                            <select class="form-control select-2" id="sources" name="sources[]" multiple="" required>
                                @foreach($sources as $s => $source)
                                    <option value="{{ $source->id }}">{{ $source->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="keywords" class="form-label">Keywords <small class="text-primary">(please use ' , ' for multiple keywords. Ex: science, sports, war updates, ... etc)</small></label>
                            <input class="form-control" type="text" id="keywords" name="keywords" value="">
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{ asset('plugins/select2/select2.full.min.js') }}"></script>
    <script type="text/javascript">
        var sources = {!! json_encode(sources()) !!};
        
        $(document).ready(function(){
            $('.select-2').select2({
                placeholder: "Select",
                allowClear: true
            });

            $('.select-2').val('').trigger('change');

            $('#countries').change(function(){
                updateSources($(this).val());
            });

            function updateSources(countries)
            {
                $('#sources').html('');
                var resetSourceInputs = '';
                $.each(sources, function(s, source){

                    if(countries.includes(source['country']))
                    {
                        resetSourceInputs += '<option value="'+source['id']+'">'+source['name']+'</option>'
                    }
                });
                $('#sources').html(resetSourceInputs);
            }
        });
    </script>
@endpush